### ISSUE TITLE
Keyed DOM-nodes get rerendered when they shouldn't?

### ISSUE THREAD

**Issue by cjh9** [jorgebucaran/patchdom#66] opened 2017-12-08 19:38 UTC
Take a look at these runnable examples, one written with petit-dom and the other with picodom:

# Picodom
```
<body>
<script src="https://unpkg.com/picodom"></script>
<script>
var { h, patch } = picodom

list = ["text0", "text1", "text2", "text3", "text4", "text5", "text6"];
oldnode = null;

function render() {
  node = h("div", {}, listElements());
  patch(oldnode, node, document.body);
  oldnode = node;
}

const listElements = () =>
  list.map((txt,idx) => {
    return h(
      "div",
      {
        onclick: () => {
          list.splice(idx, 1);
          render();
        },
        onupdate(e){
        	console.log(e)
        },
        key: txt
      },
      [txt]
    )});

render();
</script>
</body>
```

# Petit-dom
```
<body>
<script src="https://cdn.jsdelivr.net/npm/petit-dom@0.0.14/dist/petit-dom.min.js"></script>
<script>
var { h, mount, patch } = petitDom

list = ["text0", "text1", "text2", "text3", "text4", "text5", "text6"];
oldnode = h('div', {}, ['first']);
document.body.appendChild(mount(oldnode));

function render() {
  node = h("div", {}, listElements());
  patch(node, oldnode);
  oldnode = node;
}

const listElements = () =>
  list.map((txt,idx) => {
    return h(
      "div",
      {
        onclick: (e) => {
          var i = idx
          list.splice(idx, 1);
          render();
        },
        key: txt
      },
      [txt]
    )});

render();
</script>
</body>
```

Open Chrome devtools, inspect elements and click on any text label do remove it, notice that the algorithm in picodom applies dom-changes to all the text-labels after the actual label (see animated gif below). They are also logged with the onupdate hook. But with petit-dom they are not. Is this expected behavior?

![out](https://user-images.githubusercontent.com/18718330/33825278-7140deb4-de61-11e7-89cb-0d6b18188a61.gif)

**Comment by JorgeBucaran** [comment] 2017-12-09 02:11
@cjh9 Could you please write more readable code? I could edit your post and format the code for you, but then that's kind of disrespectful to the maintainer of the project.

**Comment by cjh9** [comment] 2017-12-09 17:09
@JorgeBucaran Sry, just updated the code and ran it trough prettierJS :) Ok?

**Comment by zaceno** [comment] 2017-12-11 10:34
@cjh9 Yes currently that's the behavior. If I understand what's going on correctly, it's not a bug, but a potential optimization to the patch-algorithm.

It's been discussed elsewhere (can't recall where now though), but the idea is that we should identify how much of the beginning *and end* of the list that hasn't changed, and leave those parts alone. Only apply the keyed patching algo to the middle-part where there have been changes.

(@JorgeBucaran do you know the issue where the  "prefix/suffix" thing was discussed? That's what this is about I think. Or?)

**Comment by JorgeBucaran** [comment] 2017-12-11 11:50
https://github.com/hyperapp/hyperapp/issues/216

**Comment by JorgeBucaran** [comment] 2017-12-11 19:23
@cjh9 :) Not a bug! The vnodes are just being touched by setElementProp, we are setting onclick and onupdate handlers on them on every render.

**Comment by cjh9** [comment] 2017-12-12 06:49
@zaceno @JorgeBucaran I've just debugged the thing and it looks like it is just reattaching the event listeners, so the dom-nodes are not recreated.

 However this is not why the nodes are flashing, try attaching an event listener in devtools `$0.onclick = function(){console.log('hello')}`, nothing will happen. They are flashing because the algorithm are changing their order with `insertBefore` in `patchElement`. So this has a side effect, animations will be triggered on keyed element that should not be touched. 

```
<body>
<script src="https://unpkg.com/picodom"></script>
<script>
var { h, patch } = picodom

list = ["text0", "text1", "text2", "text3", "text4", "text5", "text6"];
oldnode = null;

function render() {
  node = h("div", {}, listElements());
  patch(oldnode, node, document.body);
  oldnode = node;
}

const listElements = () =>
  list.map((txt,idx) => {
    return h(
      "div",
      {
        onclick: () => {
          list.splice(idx, 1);
          render();
        },
        class:'item',
        key: txt
      },
      [txt]
    )});

render();
</script>

<style>
@keyframes ANIMATION {
  0%   { opacity: 0; }
  100% { opacity: 1; }
}

.item {
  animation: ANIMATION 1s 1; 
}
</style>
</body>
```

![out](https://user-images.githubusercontent.com/18718330/33871012-eeb528fa-df10-11e7-894f-1363f4435564.gif)

**Comment by zaceno** [comment] 2017-12-12 07:37
@cjh9 Ah I see. And *that* is something I think could only be fixed with an algorithm that ignores the unchanged beginning *and end* of a list. The "prefix/suffix" discussion from hyperapp/hyperapp#216

**Comment by JorgeBucaran** [comment] 2017-12-12 07:49
@cjh9 Thanks for figuring it out why stuff was flashing! 👍

**Comment by jorgebucaran** [comment] 2018-02-27 16:14
https://github.com/hyperapp/hyperapp/issues/499

**Closed by jorgebucaran** 2018-02-27 16:14 UTC
Labels: BUG

**Comment by jorgebucaran** [comment] 2018-06-29 08:18
This problem is now fixed after backporting https://github.com/hyperapp/hyperapp/pull/663 from Hyperapp.

Thanks @SkaterDad! 🎉
